### ISSUE TITLE
Sorter with PagerFanta 

### ISSUE THREAD

**Issue by nfouka** [whiteoctober/Pagerfanta#256]
- I'm using your bundle with Symfony4 with ArrayAdapter, I would like to do a sorter on my data display on a list , I managed to do it with controller ORDER BY on the DQL query, except that every time I have to reload all the data from the database.
Is there a way to integrate that on twig / javascript ?
thank you in advance
cordially

**Comment by sampart** [comment]
Hi @nfouka.  You mentioned that you're using DQL.  Given that, you may find it easier to use one of the Doctrine adapters rather than the array adapter.  Here's an example: https://github.com/whiteoctober/Pagerfanta#doctrineormadapter

You should be able to add sorting using the querybuilder if using the Doctrine adapter approach.

Hope this helps, and let me know if you need more help.

**Comment by sampart** [comment]
Closing as no response.
