### ISSUE TITLE
Error in readme.md

### ISSUE THREAD

**Issue by dobrik** [whiteoctober/Pagerfanta#259]
Wront parameter name for DefaultView in readme https://github.com/whiteoctober/Pagerfanta#defaultview , prev_message instread of previous_message.

**Comment by sampart** [comment]
Hi @dobrik. `prev_message` is now used everywhere instead of `previous_message` (https://github.com/whiteoctober/Pagerfanta/pull/230).

If `prev_message` isn't working for you, please do open an issue and we'll do our best to help.  But please do check out https://github.com/whiteoctober/Pagerfanta/issues/249 first to see if that solves it.  Thanks
